Adding ACPI for Phone (1)
Project-Silicium/Silicium-ACPI pull request #20
Opened 2024-10-06 15:48 UTC by index986

### What Changed
Adding ACPI for Phone (1)

### Reason

### Checklist

* [x] Is what you changed Tested?                (Required)
* [ ] Is all the ACPI Source based on your DTS?
* [x] Are the Correct Compiler Versions used?    (Required)
* [x] Are there no References from the Compiler? (Required)

2024-10-07 13:26 UTC, Robotix22 requested changes

2024-10-07 13:26 UTC, Robotix22 commented on Platforms/Xiaomi/lavender/DSDT.dsl
Please Remove this File if the other .asl File is Used for Compiling.

2024-10-07 16:17 UTC, index986 commented on Platforms/Xiaomi/lavender/DSDT.dsl
Sorry but I dont really understand what do you mean under " other .asl File "

2024-10-12 09:37 UTC, Robotix22 commented on Platforms/Xiaomi/lavender/DSDT.dsl
In the spacewar Folder are two Files that can be Compiled
The First One is .ask and the other one is .dsl
You have to Remove the one you didn't use for making the .aml File

2024-10-12 11:40 UTC, index986 commented on Platforms/Xiaomi/lavender/DSDT.dsl
Fixed

2024-10-12 11:55 UTC, Robotix22 approved these changes

2024-10-12 11:55 UTC, merged